# FlatOut W32 & BGM Tool by Chloe @gaycoderprincess
# enjoy, nya~ :3

# Material sort priorities for .bgm models
# Higher priority values get added to the material list later than lower ones
# Usage: name=priority
# Priority can be 0 (default) to 255
[material_priorities]
light_brake=1
light_brake_l=1
light_brake_r=1
light_brake_b=2
light_brake_l_b=2
light_brake_r_b=2